# Generated by Django 5.2.4 on 2025-08-05 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('mobile_number', models.CharField(max_length=15)),
                ('ornament_type', models.CharField(max_length=100)),
                ('gross_weight', models.FloatField()),
                ('stone_weight', models.FloatField()),
                ('gold_rate', models.FloatField()),
                ('stone_price', models.FloatField()),
                ('making_charge_percent', models.FloatField()),
                ('cgst', models.FloatField()),
                ('sgst', models.FloatField()),
                ('total_price', models.FloatField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
