# Generated by Django 5.2.4 on 2025-08-05 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_remove_invoice_ornament_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='stone_weight',
        ),
        migrations.AddField(
            model_name='invoice',
            name='stone_type',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
